// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: outfits.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getPiecesByOutfitId = `-- name: GetPiecesByOutfitId :many
SELECT BIN_TO_UUID(p.id) AS piece_uuid, p.created_at, p.sizes, p.outfit_id, p.variant_id, BIN_TO_UUID(v.id) AS variant_uuid, v.id, v.created_at, v.name, v.colors, v.pattern, v.image_urls, v.product_id
FROM outfit_pieces p
JOIN product_variants v ON p.variant_id=v.id
WHERE p.outfit_id=UUID_TO_BIN(?)
ORDER BY p.created_at DESC
`

type GetPiecesByOutfitIdRow struct {
	PieceUuid   string
	CreatedAt   sql.NullTime
	Sizes       json.RawMessage
	OutfitID    []byte
	VariantID   []byte
	VariantUuid string
	ID          []byte
	CreatedAt_2 sql.NullTime
	Name        string
	Colors      json.RawMessage
	Pattern     string
	ImageUrls   json.RawMessage
	ProductID   []byte
}

func (q *Queries) GetPiecesByOutfitId(ctx context.Context, outfituuid string) ([]GetPiecesByOutfitIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getPiecesByOutfitId, outfituuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPiecesByOutfitIdRow
	for rows.Next() {
		var i GetPiecesByOutfitIdRow
		if err := rows.Scan(
			&i.PieceUuid,
			&i.CreatedAt,
			&i.Sizes,
			&i.OutfitID,
			&i.VariantID,
			&i.VariantUuid,
			&i.ID,
			&i.CreatedAt_2,
			&i.Name,
			&i.Colors,
			&i.Pattern,
			&i.ImageUrls,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
