// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: products.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createProduct = `-- name: createProduct :exec
INSERT INTO products (id, name, description, sourceUrl, available_to_buy, gender, categories, materials, image_url, profile_id)
VALUES (UUID_TO_BIN(UUID()), ?, ?, ?, ?, ?, ?, ?, ?, UUID_TO_BIN(?))
`

type createProductParams struct {
	Name           string
	Description    sql.NullString
	Sourceurl      sql.NullString
	AvailableToBuy bool
	Gender         NullProductsGender
	Categories     NullProductsCategories
	Materials      json.RawMessage
	ImageUrl       string
	ProfileUUID    string
}

func (q *Queries) createProduct(ctx context.Context, arg createProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Sourceurl,
		arg.AvailableToBuy,
		arg.Gender,
		arg.Categories,
		arg.Materials,
		arg.ImageUrl,
		arg.ProfileUUID,
	)
	return err
}

const getProductById = `-- name: getProductById :one
SELECT BIN_TO_UUID(id) AS uuid, id, created_at, name, description, sourceurl, available_to_buy, gender, categories, materials, image_url, profile_id FROM products
WHERE id = UUID_TO_BIN(?)
LIMIT 1
`

type getProductByIdRow struct {
	Uuid           string
	ID             []byte
	CreatedAt      sql.NullTime
	Name           string
	Description    sql.NullString
	Sourceurl      sql.NullString
	AvailableToBuy bool
	Gender         NullProductsGender
	Categories     NullProductsCategories
	Materials      json.RawMessage
	ImageUrl       string
	ProfileID      []byte
}

func (q *Queries) getProductById(ctx context.Context, uuid string) (getProductByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getProductById, uuid)
	var i getProductByIdRow
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Sourceurl,
		&i.AvailableToBuy,
		&i.Gender,
		&i.Categories,
		&i.Materials,
		&i.ImageUrl,
		&i.ProfileID,
	)
	return i, err
}

const updateProductById = `-- name: updateProductById :exec
UPDATE products
SET name=COALESCE(?, name),
   description=COALESCE(?,description),
   sourceUrl=COALESCE(?, sourceUrl),
   available_to_buy=COALESCE(?, available_to_buy),
   gender=COALESCE(?, gender),
   categories=COALESCE(?, categories),
   materials=COALESCE(?, materials),
   image_url=COALESCE(?, image_url)
WHERE id = UUID_TO_BIN(?)
`

type updateProductByIdParams struct {
	Name           sql.NullString
	Description    sql.NullString
	Sourceurl      sql.NullString
	AvailableToBuy sql.NullBool
	Gender         NullProductsGender
	Categories     NullProductsCategories
	Materials      json.RawMessage
	ImageUrl       sql.NullString
	Uuid           string
}

func (q *Queries) updateProductById(ctx context.Context, arg updateProductByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateProductById,
		arg.Name,
		arg.Description,
		arg.Sourceurl,
		arg.AvailableToBuy,
		arg.Gender,
		arg.Categories,
		arg.Materials,
		arg.ImageUrl,
		arg.Uuid,
	)
	return err
}
