// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: profiles.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createProfile = `-- name: CreateProfile :execlastid
INSERT INTO profiles (id, username, image_url, user_id)
VALUES (UUID_TO_BIN(UUID(), 1), ?, "https://cdn.onlinewebfonts.com/svg/img_110805.png", UUID_TO_BIN(?, 1))
`

type CreateProfileParams struct {
	Username  string
	UUIDTOBIN string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProfile, arg.Username, arg.UUIDTOBIN)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createProfileFollow = `-- name: CreateProfileFollow :exec
INSERT INTO profile_follows(follower_id, following_id)
VALUES(UUID_TO_BIN(@follower_id), UUID_TO_BIN(@following_id))
`

func (q *Queries) CreateProfileFollow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createProfileFollow)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id=UUID_TO_BIN(?, 1)
`

func (q *Queries) DeleteProfile(ctx context.Context, uuidTOBIN string) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, uuidTOBIN)
	return err
}

const deleteProfileFollow = `-- name: DeleteProfileFollow :exec
DELETE FROM profile_follows
WHERE follower_id=@follower_id AND following_id=@following_id
`

func (q *Queries) DeleteProfileFollow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteProfileFollow)
	return err
}

const getFollowerProfiles = `-- name: GetFollowerProfiles :many
SELECT BIN_TO_UUID(p.id, 1) AS uuid, p.id, p.created_at, p.username, p.image_url, p.gender, p.height_inches, p.weight_lbs, p.skin_pigmentation, p.hair_color, p.eye_color, p.size_preferences, p.user_id
FROM profiles p
JOIN profile_follows f ON p.id=f.following_id
WHERE f.following_id=UUID_TO_BIN(?)
ORDER BY f.created_at DESC
`

type GetFollowerProfilesRow struct {
	Uuid             string
	ID               []byte
	CreatedAt        sql.NullTime
	Username         string
	ImageUrl         string
	Gender           NullProfilesGender
	HeightInches     sql.NullInt32
	WeightLbs        sql.NullInt32
	SkinPigmentation sql.NullInt32
	HairColor        sql.NullString
	EyeColor         sql.NullString
	SizePreferences  json.RawMessage
	UserID           []byte
}

func (q *Queries) GetFollowerProfiles(ctx context.Context, uuidTOBIN string) ([]GetFollowerProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowerProfiles, uuidTOBIN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowerProfilesRow
	for rows.Next() {
		var i GetFollowerProfilesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.ImageUrl,
			&i.Gender,
			&i.HeightInches,
			&i.WeightLbs,
			&i.SkinPigmentation,
			&i.HairColor,
			&i.EyeColor,
			&i.SizePreferences,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingProfiles = `-- name: GetFollowingProfiles :many
SELECT BIN_TO_UUID(p.id, 1) AS uuid, p.id, p.created_at, p.username, p.image_url, p.gender, p.height_inches, p.weight_lbs, p.skin_pigmentation, p.hair_color, p.eye_color, p.size_preferences, p.user_id
FROM profiles p
JOIN profile_follows f ON p.id=f.follower_id
WHERE f.follower_id=UUID_TO_BIN(?)
ORDER BY f.created_at DESC
`

type GetFollowingProfilesRow struct {
	Uuid             string
	ID               []byte
	CreatedAt        sql.NullTime
	Username         string
	ImageUrl         string
	Gender           NullProfilesGender
	HeightInches     sql.NullInt32
	WeightLbs        sql.NullInt32
	SkinPigmentation sql.NullInt32
	HairColor        sql.NullString
	EyeColor         sql.NullString
	SizePreferences  json.RawMessage
	UserID           []byte
}

func (q *Queries) GetFollowingProfiles(ctx context.Context, uuidTOBIN string) ([]GetFollowingProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingProfiles, uuidTOBIN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingProfilesRow
	for rows.Next() {
		var i GetFollowingProfilesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.ImageUrl,
			&i.Gender,
			&i.HeightInches,
			&i.WeightLbs,
			&i.SkinPigmentation,
			&i.HairColor,
			&i.EyeColor,
			&i.SizePreferences,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT BIN_TO_UUID(p.id, 1) AS uuid,
  BIN_TO_UUID(p.user_id, 1) AS user_uuid,
  u.first_name, u.last_name, p.id, p.created_at, p.username, p.image_url, p.gender, p.height_inches, p.weight_lbs, p.skin_pigmentation, p.hair_color, p.eye_color, p.size_preferences, p.user_id
FROM profiles p
JOIN users u ON p.user_id=u.id
WHERE p.id = UUID_TO_BIN(?, 1)
LIMIT 1
`

type GetProfileByIDRow struct {
	Uuid             string
	UserUuid         string
	FirstName        string
	LastName         string
	ID               []byte
	CreatedAt        sql.NullTime
	Username         string
	ImageUrl         string
	Gender           NullProfilesGender
	HeightInches     sql.NullInt32
	WeightLbs        sql.NullInt32
	SkinPigmentation sql.NullInt32
	HairColor        sql.NullString
	EyeColor         sql.NullString
	SizePreferences  json.RawMessage
	UserID           []byte
}

func (q *Queries) GetProfileByID(ctx context.Context, uuidTOBIN string) (GetProfileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, uuidTOBIN)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.FirstName,
		&i.LastName,
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.ImageUrl,
		&i.Gender,
		&i.HeightInches,
		&i.WeightLbs,
		&i.SkinPigmentation,
		&i.HairColor,
		&i.EyeColor,
		&i.SizePreferences,
		&i.UserID,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT BIN_TO_UUID(p.id, 1) AS uuid,
  BIN_TO_UUID(p.user_id, 1) AS user_uuid,
  u.first_name, u.last_name, p.id, p.created_at, p.username, p.image_url, p.gender, p.height_inches, p.weight_lbs, p.skin_pigmentation, p.hair_color, p.eye_color, p.size_preferences, p.user_id
FROM profiles p
JOIN users u ON p.user_id=u.id
WHERE p.user_id = UUID_TO_BIN(?, 1)
LIMIT 1
`

type GetProfileByUserIDRow struct {
	Uuid             string
	UserUuid         string
	FirstName        string
	LastName         string
	ID               []byte
	CreatedAt        sql.NullTime
	Username         string
	ImageUrl         string
	Gender           NullProfilesGender
	HeightInches     sql.NullInt32
	WeightLbs        sql.NullInt32
	SkinPigmentation sql.NullInt32
	HairColor        sql.NullString
	EyeColor         sql.NullString
	SizePreferences  json.RawMessage
	UserID           []byte
}

func (q *Queries) GetProfileByUserID(ctx context.Context, uuidTOBIN string) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, uuidTOBIN)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.FirstName,
		&i.LastName,
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.ImageUrl,
		&i.Gender,
		&i.HeightInches,
		&i.WeightLbs,
		&i.SkinPigmentation,
		&i.HairColor,
		&i.EyeColor,
		&i.SizePreferences,
		&i.UserID,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET
  image_url=coalesce(?, image_url),
  gender=coalesce(?, gender),
  height_inches=coalesce(?, height_inches),
  weight_lbs=coalesce(?, weight_lbs),
  skin_pigmentation=coalesce(?, skin_pigmentation),
  hair_color=coalesce(?, hair_color),
  eye_color=coalesce(?, eye_color),
  size_preferences=coalesce(?, size_preferences)
WHERE user_id = UUID_TO_BIN(?)
`

type UpdateProfileParams struct {
	ImageUrl         sql.NullString
	Gender           NullProfilesGender
	HeightInches     sql.NullInt32
	WeightLbs        sql.NullInt32
	SkinPigmentation sql.NullInt32
	HairColor        sql.NullString
	EyeColor         sql.NullString
	SizePreferences  json.RawMessage
	UserId           string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateProfile,
		arg.ImageUrl,
		arg.Gender,
		arg.HeightInches,
		arg.WeightLbs,
		arg.SkinPigmentation,
		arg.HairColor,
		arg.EyeColor,
		arg.SizePreferences,
		arg.UserId,
	)
	return err
}
